#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():
    
    if len(sys.argv) != 2:
        sys.exit("Usage: tweets name")
    
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    analyzer = Analyzer(positives, negatives)
    tweets = get_user_timeline(sys.argv[1], 50)

    if tweets:
        for tweet in tweets:
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored(":)" + tweet, "green"))
            elif score < 0.0:
                print(colored(":(" + tweet, "red"))
            else:
                print(colored(":|" + tweet, "yellow"))
    else:
        print("sorry")
    
if __name__ == "__main__":
    main()


    
    


